server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.79.37:8848
  application:
    name: api-passenger
  redis:
    host: 123.57.79.37
    port: 6379
    database: 0