server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.79.37:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.79.37:3306/service-driver-user?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  application:
    name: service-driver-user
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl