server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.79.37:3306/service-map?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.79.37:8848
  application:
    name: service-map
#自定义的key value
amap:
  key: 554407fe9befe3540ef0808fe34dffd3
  #服务id，服务名称：测试服务01
  sid: 856998
